# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20191213_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='city',
        ),
    ]
