# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20191214_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='category/'),
        ),
    ]
