# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20191215_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
